
     <main class="container-fluid">
          <h2 class="text-center">Ajouter une chambre</h2>

          <form action="" method="post" enctype="multipart/form-data">
               <div class="row">
                    <div class="form-group col-6">
                         <label for="">Prix</label>
                         <input type="text" name="prix" class="form-control" value="<?= $prix ?? '' ?>">
                         <?= ( isset($prix) && $prix >= 50 && ctype_digit($prix) )
                              ? '' 
                              : '<div class="text-danger"> prix doit être >= 50 €</div>' ?>
                    </div>
                    
                    <div class="form-group col-6">
                         <label for="">Nombre de lits</label>
                         <input type="text" name="nbLits" class="form-control" value="<?= $nbLits ?? ''?>">
                         <?php if( !isset($nbLits) || $nbLits < 1 || !ctype_digit($nbLits)): ?> 
                              <div class="text-danger"> nbre lits doit être >= 1</div>
                         <?php endif; ?>
                         
                    </div>

                    <div class="form-group col-6">
                         <label for="">Superficie</label>
                         <input type="text" name="superficie" class="form-control" value="<?= $superficie ?? '' ?>">
                         <?= ( isset($superficie) && $superficie >= 30 && ctype_digit($superficie) )
                              ? '' 
                              : '<div class="text-danger"> la superficie doit être >= 30</div>' ?>
                    </div>

                    
                    <div class="form-group col-6">
                         <label for="">Image</label>
                         <input type="file" name="image" class="form-control">
                    </div>
               </div>
               <div class="row">
                    <div class="form-group col-4">
                         <label for="">Description</label>
                         <textarea name="description" rows="6" class="form-control"><?= $description ?? "" ?></textarea>
                         <?= isset($description) && strlen( trim($description) ) < 10
                              ? '<div class="text-danger"> la description doit faire 10 caractères</div>' 
                              : '' ?>
                    </div>
               </div>

               <input type="submit" class="btn btn-success mt-3">
          </form>

          

     </main>