
     <main class="container-fluid">
          <h2 class="text-center">Connexion</h2>

          <form action="contact.php" method="post">
               <div class="row">
                    <div class="form-group col-6">
                         <label for="">Login</label>
                         <input type="text" name="login" value="login" class="form-control">
                    </div>

                    
                    <div class="form-group col-6">
                         <label for="">Passsword</label>
                         <input type="password" name="mdp" value="mdp"  class="form-control">
                    </div>

                    
               </div>
               <input type="submit" name="connection" value="connection" class="btn btn-success mt-3">
          </form>

          

     </main>