
     <main class="container-fluid mb-5">
          <h2 class="text-center">Réservez parmis cette sublime chambre</h2>

          
          <form action="" method="post">
               
               <div class="row">
                    <div class="form-group col-6">
                         <label for="">Nom</label>
                         <input type="text" name="nom" class="form-control">
                    </div>

                    
                    <div class="form-group col-6">
                         <label for="">Prénom</label>
                         <input type="text" name="prenom" class="form-control">
                    </div>

                    <div class="form-group col-6">
                         <label for="">Email</label>
                         <input type="email" name="email" class="form-control">
                    </div>

                    
                    <div class="form-group col-6">
                         <label for="">Téléphone</label>
                         <input type="text" name="tel" class="form-control">
                    </div>
                    <div class="form-group col-6">
                         <label for="">login</label>
                         <input type="text" name="login" class="form-control">
                    </div>
                    <div class="form-group col-6">
                         <label for="">mot de pase</label>
                         <input type="text" name="mdp" class="form-control">
                    </div>
               </div>
               <div class="row">
                    <div class="form-group col-4">
                         <label for="">Adresse</label>
                         <input type="text" name="adresse" class="form-control">
                    </div>

                    
                    <div class="form-group col-4">
                         <label for="">Code postal</label>
                         <input type="text" name="cp" class="form-control">
                    </div>
                    <div class="form-group col-4">
                         <label for="">Ville</label>
                         <input type="text" name="ville" class="form-control">
                    </div>
                    <div class="form-group col-4">
                         <label for="">statut</label>
                         <input type="text" name="statut" class="form-control">
                    </div>
               </div>

               
               
               <input type="submit" name="connection"class="btn btn-success mt-3">
          </form>
     </main>

    
          

     </script>